make:
	gcc * -I /usr/local/include/igraph -L /usr/local/lib -ligraph

clean:
	rm global.h.gch
	rm a.out

test:
	./a.out /Users/zilixiang/SDL/tie_range/data/Texas84.graphml /Users/zilixiang/SDL/tierobustness/data/o.graphml
